DavLockDB /usr/local/apache2/var/DavLock

<VirtualHost *:80>
    ServerName localhost

    Alias /webdav /var/webdav

    <Directory /var/webdav>
        DAV On
        Options Indexes
        AuthType Basic
        AuthName "WebDAV"
        AuthUserFile /usr/local/apache2/conf/.htpasswd
        Require valid-user
    </Directory>
</VirtualHost>